
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: dollarsandlife
      POSTGRES_USER: sean
      POSTGRES_PASSWORD: paul12
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://sean:paul12@db:5432/dollarsandlife
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
